co:
  default:
    all_saints_day:
    ascension_day:
    assumption_of_mary:
    battle_of_boyaca:
    christmas:
    columbus_day:
    corpus_christi:
    epiphany:
    good_friday:
    immaculate_conception_day:
    independence_day:
    independence_of_cartagena:
    labor_day:
    maundy_thursday:
    new_year:
    sacred_heart:
    saint_josephs_day:
    saint_peter_and_saint_paul: